#!/bin/bash
# Snapshot the functions exported by the floor Xcode's libIndexStore into
# ci/libindexstore-floor.symbols. Run once whenever BuildInfo.minimumXcode changes,
# using the oldest point release of that Xcode (e.g. 16.0, not 16.4).
#
# Usage: scripts/capture-libindexstore-floor.sh /Applications/Xcode-16.0.app
set -euo pipefail

app="${1:?usage: capture-libindexstore-floor.sh /path/to/Xcode.app}"
root="$(cd "$(dirname "$0")/.." && pwd)"
lib="$app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libIndexStore.dylib"
[[ -f "$lib" ]] || { echo "FAIL: missing $lib" >&2; exit 1; }

version="$(defaults read "$app/Contents/Info" CFBundleShortVersionString)"
build="$(defaults read "$app/Contents/version" ProductBuildVersion 2>/dev/null || echo unknown)"

{
  echo "# Functions exported by libIndexStore in the oldest supported Xcode."
  echo "# Generated by scripts/capture-libindexstore-floor.sh; do not edit by hand."
  echo "# xcode: $version ($build)"
  nm -gU "$lib" | awk '$3 ~ /^_indexstore_/ { sub(/^_indexstore_/, "", $3); print $3 }' | sort -u
} >"$root/ci/libindexstore-floor.symbols"

echo "wrote ci/libindexstore-floor.symbols for Xcode $version ($build)"
